// Package main provides the entry point for the slot CLI application.
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/slot/internal/cli"
)

// version holds the application version, set during build time.
var version = "unknown - unofficial & generated by unknown"

// main is the entry point for the CLI application.
func main() {
	if err := cli.Execute(version); err != nil {
		fmt.Fprintln(os.Stderr, err)

		os.Exit(1)
	}

	os.Exit(0)
}
