/*
Slot saves and renders named shell commands with Go template substitution.

Store frequently used commands with template variables and tags for quick execution.
Render commands with variable substitution and integrate with your shell for seamless workflow.

Usage:

	slot [command] [flags]

Use "slot --help" for more information.
*/
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/slot/internal/cli"
)

// version is the application version injected at build time.
var version = "unknown - unofficial & generated by unknown"

// main is the entry point of the application.
func main() {
	if err := cli.Execute(version); err != nil {
		fmt.Fprintln(os.Stderr, err)

		os.Exit(1)
	}

	os.Exit(0)
}
