name: slot

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  info:
    uses: idelchi/devenv/.github/workflows/info.yml@main

  verify:
    uses: idelchi/devenv/.github/workflows/task.yml@main
    needs: info
